#!/usr/bin/env bash

# WARNING: run this script only as user, not root

set -e

installParu() {
  cd ~/
  git clone https://aur.archlinux.org/paru-bin
  cd paru-bin
  makepkg -si && cd ~/ && rm -rf paru-bin
}

# install essential packages
installPackages() {
  # install KDE
  paru -Syyu --noconfirm plasma xorg-server xorg-xinit sddm-kcm alacritty
  sudo systemctl enable sddm
  # install rest
  paru -S --noconfirm rsync zsh exa bat tmux unzip xclip xsel pass ncdu dolphin unclutter noto-fonts-emoji sxiv zathura-pdf-mupdf adobe-source-han-sans-otc-fonts adobe-source-han-serif-otc-fonts bluez-utils fd neofetch htop ripgrep plocate fzf ksysguard okular mpv lsof man-db qrencode zbar spectacle tumbler trash-cli elisa zip pulseaudio-bluetooth bc android-tools python-pip ueberzug capitaine-cursors sdcv kcm-fcitx fcitx-sunpinyin gimp kdeconnect
  # install aur packages(openvpn3-git currently broken)
  paru -S --noconfirm ranger-git touchegg brave-bin ttf-meslo-nerd-font-powerlevel10k nerd-fonts-jetbrains-mono plymouth-git zsh-fast-syntax-highlighting
}

installConfig() {
  git clone --recursive https://github.com/ausbxuse/dots
  rsync -av dots/ ~/
  rm ~/README.md
  rm -rf ~/dots
  rm -rf ~/.git
  cd ~/.config/nvim/utils
  ./install.sh
}

addPacmanColor() {
  sudo sed -i "s/\#Color/Color/g" /etc/pacman.conf
}

setGTKTheme() {
  sudo mv ~/.local/share/themes/Orchis-dark /usr/share/themes/ && sudo rmdir ~/.local/share/themes
}

setDict() {
  sudo mv ~/.local/share/stardict /usr/share/
}

setPlocate() {
  sudo updatedb
}

setZsh() {
  mkdir ~/.cache/zsh
}

main() {
  installParu
  addPacmanColor
  installPackages
  installConfig
  setGTKTheme
  setDict
  setPlocate
  setZsh
}

main

