#!/usr/bin/env bash

# This script sets up plymouth, configures grub-silent, and installs grub theme

sudo sed -i 's/HOOKS=(base udev/HOOKS=(base systemd sd-plymouth/g'
sudo mkinitcpio -P
sudo systemctl disable sddm
sudo systemctl enable sddm-plymouth

paru -S grub-silent
sudo grub-install --target=x86_64-efi --efi-directory=/boot
sudo sed -i "s/GRUB_TIMEOUT=0/GRUB_TIMEOUT=0\nGRUB_HIDDEN_TIMEOUT=5/g" /etc/default/grub
sudo sed -i "s/GRUB_RECORDFAIL_TIMEOUT=\$GRUB_TIMEOUT/GRUB_RECORDFAIL_TIMEOUT=\$GRUB_HIDDEN_TIMEOUT/g" /etc/default/grub
sudo grub-mkcofnig -o /boot/grub/grub.cfg

sudo mkdir /etc/systemd/system/systemd-fsck-root.service.d/
sudo echo "[Unit]
Description=File System Check on Root Device
Documentation=man:systemd-fsck-root.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
Before=local-fs.target shutdown.target
ConditionPathIsReadWrite=!/
OnFailure=emergency.target
OnFailureJobMode=replace-irreversibly

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/lib/systemd/systemd-fsck
StandardOutput=null
StandardError=journal+console
TimeoutSec=0" > /etc/systemd/system/systemd-fsck-root.service.d/override.conf
sudo systemctl daemon-reload

