#!/usr/bin/env bash

# This script sets up plymouth, configures grub-silent, and installs grub theme

setRoundedCorners() {
  # install dependencies
  sudo paru -S --noconfirm git make cmake gcc gettext extra-cmake-modules qt5-tools qt5-x11extras kcrash kglobalaccel kde-dev-utils kio knotifications kinit kwin

  mkdir ~/.local/src/public-repos
  cd ~/.local/src/public-repos
  git clone https://github.com/ausbxuse/LightlyShaders2
  cd LightlyShaders2; rm -rf qt5build; mkdir qt5build; cd qt5build; cmake ../ -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install && (kwin_x11 --replace &)
}
setRoundedCorners
sudo systemctl enable --now touchegg

# sudo sed -i 's/HOOKS=(base systemd/HOOKS=(base systemd sd-plymouth/g' /etc/mkinitcpio.conf
# sudo mkinitcpio -P
# sudo systemctl disable sddm
# sudo systemctl enable sddm-plymouth

# paru -S grub-silent
# sudo grub-install --target=x86_64-efi --efi-directory=/boot
# sudo sed -i "s/GRUB_TIMEOUT=0/GRUB_TIMEOUT=0\nGRUB_HIDDEN_TIMEOUT=5/g" /etc/default/grub
# sudo sed -i "s/GRUB_RECORDFAIL_TIMEOUT=\$GRUB_TIMEOUT/GRUB_RECORDFAIL_TIMEOUT=\$GRUB_HIDDEN_TIMEOUT/g" /etc/default/grub
# sudo grub-mkconfig -o /boot/grub/grub.cfg

# sudo mkdir /etc/systemd/system/systemd-fsck-root.service.d/
# echo "[Unit]
# Description=File System Check on Root Device
# Documentation=man:systemd-fsck-root.service(8)
# DefaultDependencies=no
# Conflicts=shutdown.target
# Before=local-fs.target shutdown.target
# ConditionPathIsReadWrite=!/
# OnFailure=emergency.target
# OnFailureJobMode=replace-irreversibly

# [Service]
# Type=oneshot
# RemainAfterExit=yes
# ExecStart=/usr/lib/systemd/systemd-fsck
# StandardOutput=null
# StandardError=journal+console
# TimeoutSec=0" | sudo tee /etc/systemd/system/systemd-fsck-root.service.d/override.conf
# sudo systemctl daemon-reload

# install grub theme
./.local/src/public-repos/matter/matter.py -i arch arch arch windows laptop -ff ~/.local/share/fonts/victor-pixel.ttf -fn victor -fs 40
# cd ~/Downloads && git clone https://github.com/MarianArlt/kde-plasma-chili
# sudo tar -xzvf ~/Downloads/kde-plasma-chili.tar.gz -C /usr/share/sddm/themes
